name: release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: prep
        run: |
          echo ::set-output name=tags::${GITHUB_REF#refs/tags/v}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        run: |
          docker login ghcr.io --username ${GITHUB_ACTOR} --password ${GITHUB_TOKEN}
          TAG=${{ steps.prep.outputs.tags }} docker buildx bake --push
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
